package com.wpsnetwork.entidades;
// Generated 07-mar-2016 12:09:42 by Hibernate Tools 4.0.0

import java.time.LocalDate;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table( name = "PEDIDO")
public class Pedido implements java.io.Serializable {

	private int id;
	private Cliente cliente;
	private LocalDate fecha;
	private String info;

	public Pedido() {
	}

	public Pedido(int id, Cliente cliente, LocalDate fecha, String info) {
		this.id = id;
		this.cliente = cliente;
		this.fecha = fecha;
		this.info = info;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="pedido_seq")
	@SequenceGenerator(name = "pedido_seq", sequenceName = "PEDIDO_ID_SEQ", allocationSize = 1)
	@Column(name = "ID")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="IDCLIENTE", nullable=false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "FECHA")
	public LocalDate getFecha() {
		return this.fecha;
	}

	public void setFecha(LocalDate fecha) {
		this.fecha = fecha;
	}

	@Column(name="INFO")
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Override
	public String toString() {
		return "Pedido [id=" + id + ", fecha=" + fecha + ", info=" + info + "]";
	}

	
}
